// AUTO-GENERATED by Craft Creator
onEvent('recipes', event => {
    // REMOVED-RECIPES-START
    // ADDED-RECIPES-START
	// crafting-recipes
	event.custom({"type":"minecraft:crafting_shaped","pattern":["GEX","MBM","GEX"],"key":{"M":{"item":"integratedtunnels:part_interface_item"},"B":{"item":"integrateddynamics:crystalized_chorus_block"},"X":{"item":"projecte:high_covalence_dust"},"E":{"item":"projecte:medium_covalence_dust"},"G":{"item":"projecte:low_covalence_dust"}},"result":{"item":"projectexpansion:basic_emc_link","count":1}})
	event.custom({"type":"minecraft:crafting_shaped","pattern":["MBM"],"key":{"B":{"item":"minecraft:copper_ingot"},"M":{"item":"minecraft:iron_ingot"}},"result":{"item":"mekanism:basic_thermodynamic_conductor","count":8}})
	event.custom({"type":"minecraft:crafting_shaped","pattern":["MBM"],"key":{"B":{"item":"minecraft:piston"},"M":{"item":"minecraft:iron_ingot"}},"result":{"item":"mekanism:basic_logistical_transporter","count":8}})
	event.custom({"type":"minecraft:crafting_shaped","pattern":["MBM"],"key":{"M":{"item":"minecraft:iron_ingot"},"B":{"tag":"forge:glass"}},"result":{"item":"mekanism:basic_pressurized_tube","count":8}})
	event.custom({"type":"minecraft:crafting_shaped","pattern":["MBM"],"key":{"M":{"item":"minecraft:iron_ingot"},"B":{"item":"minecraft:bucket"}},"result":{"item":"mekanism:basic_mechanical_pipe","count":8}})
	event.custom({"type":"minecraft:crafting_shaped","pattern":["MBM"],"key":{"M":{"item":"minecraft:iron_ingot"},"B":{"item":"minecraft:redstone"}},"result":{"item":"mekanism:basic_universal_cable","count":8}})
	
})
